// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klfelhvyycehehdekeiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsZmVsaHZ5eWNlaGVoZGVrZWl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDkyNDYsImV4cCI6MjA1OTc4NTI0Nn0.fExnoq4qpqhZh8BzhNVppWieuhx0daNXYK5bdXpf_N8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);